[workspace]
resolver = "3"
members = [
    "crates/uenv",
    "crates/uenv_cli",
]

[workspace.package]
version = "0.0.0-1"
edition = "2024"
authors = ["SourceTrait <development@sourcetrait.com"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/uenv"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "uenv", "environment", "env"]

[workspace.dependencies]
